### ISSUE TITLE
Crash with 1.19.3

### ISSUE THREAD

**Issue by Jh16** [ShayBox/Durability101#12]
So I've narrowed down my crash problem with the 1.19.3 version.

How you can replicate:
-make a world or join a world
-grab any tool/weapon/gear
-damage it then try opening your inventory or if it's viewable

Basically, whenever the display of durability occurs it crashes.

**Comment by ShayBox** [comment]
Is this Forge or Fabric?

**Comment by Jh16** [comment]
My apologies, Fabric

**Comment by ShayBox** [comment]
[Durability101-fabric-1.19.3-0.0.4.zip](https://github.com/ShayBox/Durability101/files/10203751/Durability101-fabric-1.19.3-0.0.4.zip)
Try this, rename from .zip to .jar, GitHub doesn't allow uploading jar files

**Comment by Jh16** [comment]
Working perfectly now without any crashes. Thankies :)

Edit:
So what ended up being the problem?

**Comment by ShayBox** [comment]
It appears some Mappings changed between 1.19.2 and 1.19.3, Usually versions work without issue

**Comment by Jh16** [comment]
Alright, well either way much appreciated! :D

**Comment by venaminecraft** [comment]
Thank you @ShayBox 😊
