### ISSUE TITLE
[1.20.1] Conflict With ImmediatelyFast

### ISSUE THREAD

**Issue by RConTRS** [ShayBox/Durability101#16]
when using ImmediatelyFast mod there's an issue
the durability counter is dim or barely visible in the hotbar, but not in the inventory GUI

![1](https://github.com/ShayBox/Durability101/assets/97401001/047eb092-e0d2-4b39-916a-4df4aefc4aec)

![2](https://github.com/ShayBox/Durability101/assets/97401001/f0bf5792-e349-4dcb-bfe1-65aadc325cff)

using only the 2 mods

**Comment by Leclowndu93150** [comment]
it's the HUD Batching config

**Comment by RConTRS** [comment]
turned off hud batching in config and it fixed it, thanks!
