### ISSUE TITLE
Is it possible to turn off the "tool breaking" sound completely and between sessions of Minecraft?

### ISSUE THREAD

**Issue by kedamono** [ShayBox/Durability101#5]
When I use Ctrl-H to turn the weapon breaking sound down, the next time I start Minecraft, the settings are not saved. I looked in the config file and there's no setting to turn off this sound. It's very annoying.

**Comment by ShayBox** [comment]
There's no breaking sound or control to change that, minecraft has one by default, but you're probably looking for a different mod you have installed.

**Comment by kedamono** [comment]
Sorry, it's Durability Viewer! Closing bug.
