### ISSUE TITLE
Durability numbers are visible through tooltips.

### ISSUE THREAD

**Issue by AliahX** [ShayBox/Durability101#7]
title

**Comment by ShayBox** [comment]
Yeah, same as #3, I can't fix it, the game keeps track of the Z layer in an incremental variable that I can't reasonable get access to, so I just have to enter a static value that works with the vanilla testing, but other mods offset this number, different versions of the game change this number, it's unreliable, but there's just no good way to fix it without rewriting the mod to use Sponge mixins

**Comment by ZephaniahNoah** [comment]
Can you access the z layer value with reflection? Or are mixins the only way?

**Comment by ShayBox** [comment]
There's probably a way but I don't know how, I might remake all versions of the mod one day using mixins now that they're supported for every version, that would allow me to add some features and a config

**Comment by ShayBox** [comment]
The latest versions of Forge use their new Decorators API, which solves this issue, and I will be switching the latest versions of Fabric to their similarly new API.
